### ISSUE TITLE
giteaCpuLimit not working as expected

### ISSUE THREAD

**Issue by panostzemis** [redhat-gpte-devopsautomation/gitea-operator#2]
Hello developers,

I am trying to use your operator on version 1.1.0 but upon gitea instance a have a problem with giteaCpuLimit ( and postgresqlCpuLimit & requests ).
Documentation is not clear on what type: object it need.

I tried a lot of ways but none of them was successful. ( OFC something like giteaCpuRequest: 1500m is not working )

Not sure if it's an error on the definition on don't know the key value for the object needed.

If everything is correct please provide an example

Thank you in advance

**Comment by wkulhanek** [comment]
Thank you @panostzemis . This slipped back in on the last update. But actually CPULimit was never working anyway... All that's fixed now. And the operator can be upgraded using OLM. You'll have to re-apply the CatalogSource which now points to the `:latest` catalog image - so every time there will be an update it will be offered in the OperatorHub in OpenShift.

There are a ton more features (settings) in this version as well.
