### ISSUE TITLE
Allow ALLOW_LOCALNETWORKS flag to be configurable

### ISSUE THREAD

**Issue by mixpix3ls** [redhat-gpte-devopsautomation/gitea-operator#4]
Gitea does not allow migrating repositories orginating from a private IP. This can be changed by toggling the ALLOW_LOCALNETWORKS flag. Currently, there is no way to toggle this setting in the operator. Would it be fairly easy to add it? If so, could it be added in an upcoming release?

**Comment by mixpix3ls** [comment]
I see that it could just be added here:

https://github.com/redhat-gpte-devopsautomation/gitea-operator/blob/e7f00fd17195d379b5838e3c3b85a96544a8d68f/roles/gitea-ocp/templates/config_map.j2

**Comment by wkulhanek** [comment]
Thanks for the suggestion @mixpix3ls . This should now be working with Operator 1.2.3. If your catalogsource is pointing to `latest` the operator should get upgraded automatically.
